name: Bug Report
description: Report a bug or issue in the codebase
title: "[BUG] Brief description"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        
        Thank you for helping improve the THUG source code project!
        
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What went wrong?
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Build with '...'
        3. Run '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should happen instead?
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the codebase is affected?
      options:
        - Build System
        - Documentation
        - Core Utilities
        - Graphics System
        - Audio System
        - Physics System
        - Scripting System
        - Win32 Platform
        - Other (specify in description)
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Provide information about your environment:
      value: |
        - OS: [e.g., Windows 10, Ubuntu 22.04, macOS 13]
        - Compiler: [e.g., MSVC 2019, GCC 11, Clang 14]
        - CMake version: [e.g., 3.20]
        - Build type: [Debug/Release]
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Output
      description: Paste any relevant error messages or logs
      render: shell
      placeholder: Paste error output here
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Screenshots, related issues, etc.
    validations:
      required: false
